#!/bin/bash
# A "where am I?" script. Prints "context/namespace". I use it in my shell prompt.
# Author: Katrina Verey (github.com/KnVerey)

if which kubectl > /dev/null; then
  cname=`kubectl config current-context`
  args="--output=jsonpath={.contexts[?(@.name == \"${cname}\")].context.namespace}"
  namespace=$(kubectl config view "${args}")
  if [ -z $namespace ]; then
    namespace="default"
  fi
  echo "${cname}/${namespace}"
fi
